### ISSUE TITLE
[addtool] Faraday security

### ISSUE THREAD

**Issue by Flormigliorisi** [gwen001/offsectools_www#336]
[short_descr] Open Source Vulnerability Management and Orchestration Platform [/short_descr]
[link] https://github.com/infobyte/faraday[/link]
[tags] orchestration,cve,cybersecurity [/tags]
[image]https://user-images.githubusercontent.com/112972715/209713920-83e63b2d-edfd-4d72-b44e-4e53191b4eab.png[/image]
[long_descr] A single platform for Vulnerability Management, built alongside security specialists and designed to speed up detection & triage of vulnerabilities [/long_descr]

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
Feel free to check one of the 300 issues already closed to see how it should be done.
Also, you don't have to recreate a new issue at every change, just edit the issue in place.

Thank you for your understanding.

**Comment by gwen001** [comment]
Problem occured with the following fields: picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/faraday-security

Thank you for your contribution!
