### ISSUE TITLE
[addtool] EMBA

### ISSUE THREAD

**Issue by m-1-k-3** [gwen001/offsectools_www#422]
[short_descr]The security analyzer for firmware of embedded devices[/short_descr]
[link]https://github.com/e-m-b-a/emba[/link]
[tags]firmware, IoT, embedded, Linux, scanner, SBOM[/tags]
[image]https://raw.githubusercontent.com/e-m-b-a/emba/master/helpers/emba.svg[/image]
[long_descr]EMBA is designed as the central firmware analysis tool for penetration testers. It supports the complete security analysis process starting with the firmware extraction process, doing static analysis and dynamic analysis via emulation and finally generating a web report. EMBA automatically discovers possible weak spots and vulnerabilities in firmware. Examples are insecure binaries, old and outdated software components, potentially vulnerable scripts or hard-coded passwords. EMBA is a command line tool with the option to generate an easy to use web report for further analysis.[/long_descr]

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
You can also check one of the 400 issues already closed to see how it's supposed to be.

Thank you for your understanding.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/emba

Thank you for your contribution!
