### ISSUE TITLE
Revshells.com

### ISSUE THREAD

**Issue by 0dayCTF** [gwen001/offsectools_www#488]
[link]https://revshells.com [/link]
[tags]reverse shell generator, revshells, reverse shell, rev shell generator[/tags]
[short_descr]Hosted Reverse Shell generator with a ton of functionality. -- (Great for CTFs) [/short_descr]
[long_descr] [/long_descr] 
[image] https://user-images.githubusercontent.com/44453666/210595932-8fbd73c7-d981-41fc-9086-4c40122dd4d8.png [/image]

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
You can also check one of the 400 issues already closed to see how it's supposed to be or use the issue template created for that purpose.

Thank you for your understanding.

**Comment by gwen001** [comment]
Still no.

I created an issue template to make it easier. Feel free to use it to avoid mistakes.

Thank you.

**Comment by 0dayCTF** [comment]
I don’t see it, it’s okay. I appreciate the help.

**Comment by gwen001** [comment]
When you click on the button "New issue" you'll get that component:
<img width="1247" alt="Screenshot 2023-01-09 at 10 01 23" src="https://user-images.githubusercontent.com/5347721/211272146-806ff6da-7f49-4a11-87a4-f5bd4364996d.png">

Then click on the button "Get started" and that's it.

**Comment by gwen001** [comment]
https://offsec.tools/tool/revshells
