### ISSUE TITLE
[addtool] moniorg

### ISSUE THREAD

**Issue by yousseflahouifi** [gwen001/offsectools_www#939]
[homepage]https://github.com/yousseflahouifi/moniorg[/homepage]
[tags]reconnaissance,monitoring[/tags]
[short_descr]moniorg is a tool that leverages crt.sh website to monitor domains of a target[/short_descr]
[long_descr]By looking through CT logs an attacker can gather a lot of information about organization's infrastructure i.e. internal domains,email addresses in a completly passive manner.
moniorg leverage certificate transparency logs to monitor for newly issued domains based on organization field in their SSL certificate .[/long_descr]
[image]https://miro.medium.com/v2/resize:fit:640/format:webp/1*eoo4hCi6YUzrIW0O3uc47A.png[/image]

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
You can also check one of the 400 issues already closed to see how it's supposed to be or use the issue template created for that purpose.

Thank you for your understanding.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/moniorg

Thank you for your contribution!
